apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: athenz-zms-db
spec:
  containers:
  - name: athenz-zms-db
    image: wzyahoo/athenz-zms-db
    args:
      - --skip-host-cache"
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: athenz-zms-db-root-secret
            key: password
      - name: ZMS_DB_ADMIN
        valueFrom:
          secretKeyRef:
            name: athenz-zms-db-admin-secret
            key: username
      - name: ZMS_DB_ADMIN_PASS
        valueFrom:
          secretKeyRef:
            name: athenz-zms-db-admin-secret
            key: password
    volumeMounts:
      - name: athenz-zms-db-config
        mountPath: /etc/mysql/conf.d
        subPath: zms-db.cnf
    volumeMounts:
      - name: init-zms-admin
        mountPath: /home/mysql
        subPath: init-zms-admin.sh
  volumes:
    - name: athenz-zms-db-config
      configMap:
        name: athenz-zms-db-config
  volumes:
    - name: init-zms-admin
      configMap:
        name: init-zms-admin
  lifecycle:
    postStart:
      exec:
        command: ["/bin/sh", "/home/mysql/init-zms-admin.sh"]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-zms-admin
data:
  init-zms-admin.sh: |
    #!/bin/sh

    set -eu
    set -o pipefail

    mysql \
      --database=zms_server \
      --user=root --password="${MYSQL_ROOT_PASSWORD}" \
      --execute="CREATE USER '${ZMS_DB_ADMIN}'@'%' IDENTIFIED BY '${ZMS_DB_ADMIN_PASS}'; GRANT ALL PRIVILEGES ON zms_server.* TO '${ZMS_DB_ADMIN}'@'%'; FLUSH PRIVILEGES;"
    mysql \
      --database=mysql \
      --user=root --password="${MYSQL_ROOT_PASSWORD}" \
      --execute="DELETE FROM user WHERE user = 'root' AND host = '%';"
    mysql \
      --database=mysql \
      --user=root --password="${MYSQL_ROOT_PASSWORD}" \
      --execute="SELECT user, host FROM user;"
