apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "athenz-zms.fullname" . }}
  labels:
    app: "{{ template "athenz-zms.name" . }}"
    chart: "{{ template "athenz-zms.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ template "athenz-zms.name" . }}
      release: {{ .Release.Name | quote }}
  {{- if .Values.updateStrategy }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "athenz-zms.name" . }}
        chart: {{ template "athenz-zms.chart" . }}
        release: {{ .Release.Name | quote }}
      {{- if .Values.podAnnotations }}
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
{{- include "athenz-zms.imagePullSecrets" . | indent 6 }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      initContainers:
        - name: tls-keystore
          image: {{ template "athenz-zms.setupImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: ZMS_KEYSTORE_PATH
              value: /opt/athenz/zms/var/certs/zms_keystore.pkcs12
            - name: ZMS_KEYSTORE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "athenz-zms.secretName" . }}
                  key: keystore
            - name: ZMS_CERT_PATH
              value: /opt/athenz/zms/var/tls/tls.crt
            - name: ZMS_CERT_KEY_PATH
              value: /opt/athenz/zms/var/tls/tls.key
          command:
            - "/bin/sh"
            - "-c"
            - >-
              openssl pkcs12 -export -noiter -nomaciter -out "${ZMS_KEYSTORE_PATH}" -passout "pass:${ZMS_KEYSTORE_PASS}" -in "${ZMS_CERT_PATH}" -inkey "${ZMS_CERT_KEY_PATH}"
          volumeMounts:
            - name: tls
              mountPath: /opt/athenz/zms/var/tls
            - name: tls-stores
              mountPath: /opt/athenz/zms/var/certs
        - name: tls-truststore
          image: {{ template "athenz-zms.setupImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: ZMS_TRUSTSTORE_PATH
              value: /opt/athenz/zms/var/certs/zms_truststore.jks
            - name: ZMS_TRUSTSTORE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "athenz-zms.secretName" . }}
                  key: truststore
          command:
            - "/bin/sh"
            - "-c"
            - >-
              for ca in /opt/athenz/zms/var/tls/CAs/*.pem; do openssl x509 -outform pem -in "${ca}" | keytool -importcert -noprompt -keystore "${ZMS_TRUSTSTORE_PATH}" -storepass "${ZMS_TRUSTSTORE_PASS}" -storetype JKS -alias "$(basename ${ca})"; done
          volumeMounts:
            - name: tls-ca
              mountPath: /opt/athenz/zms/var/tls/CAs
            - name: tls-stores
              mountPath: /opt/athenz/zms/var/certs
        - name: wait-for-master-db
          image: {{ template "athenz-zms.mariadb.image" . }}
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy | quote }}
          command:
            - "/bin/sh"
            - "/bin/wait-for-mysql.sh"
            - "--user='root'"
            - {{ printf "--host=%s" (include "athenz-zms.jdbc.master.host" .) }}
            - {{ printf "--port=%s" (include "athenz-zms.jdbc.port" .) }}
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ template "athenz-zms.mariadb.fullname" . }}
                  key: mariadb-root-password
          volumeMounts:
            - name: master-db-cnf
              mountPath: /opt/bitnami/mariadb/conf/my.cnf
              subPath: my.cnf
            - name: script
              mountPath: /bin/wait-for-mysql.sh
              subPath: wait-for-mysql.sh
        {{- if .Values.mariadb.replication.enabled }}
        - name: wait-for-slave-db
          image: {{ template "athenz-zms.mariadb.image" . }}
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy | quote }}
          command:
            - "/bin/sh"
            - "/bin/wait-for-mysql.sh"
            - {{ printf "--user=%s" .Values.mariadb.replication.user }}
            - {{ printf "--host=%s" (include "athenz-zms.jdbc.slave.host" .) }}
            - {{ printf "--port=%s" (include "athenz-zms.jdbc.port" .) }}
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ template "athenz-zms.mariadb.fullname" . }}
                  key: mariadb-replication-password
          volumeMounts:
            - name: slave-db-cnf
              mountPath: /opt/bitnami/mariadb/conf/my.cnf
              subPath: my.cnf
            - name: script
              mountPath: /bin/wait-for-mysql.sh
              subPath: wait-for-mysql.sh
        {{- end }}
        {{- if .Values.extraInitContainers }}
{{ tpl .Values.extraInitContainers . | indent 8 }}
        {{- end }}
      containers:
        - name: zms
          image: wzyahoo/athenz-zms-server
          env:
            - name: ZMS_DB_ADMIN_PASS
              value: {{ .Values.mariadb.db.password }}
            - name: ZMS_RODB_ADMIN_PASS
              value: {{ .Values.mariadb.db.password }}
            - name: ZMS_KEYSTORE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "athenz-zms.secretName" . }}
                  key: keystore
            - name: ZMS_TRUSTSTORE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "athenz-zms.secretName" . }}
                  key: truststore
            - name: ZMS_PORT
              value: "4443"
          ports:
            - name: zms
              containerPort: 4443
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: /zms/v1/status
              port: zms
              scheme: HTTPS
          volumeMounts:
            - name: config
              mountPath: /opt/athenz/zms/conf/zms_server
            - name: zms-key
              mountPath: /opt/athenz/zms/var/keys
            - name: tls-stores
              mountPath: /opt/athenz/zms/var/certs
            - name: log
              mountPath: /opt/athenz/zms/logs/zms_server
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: master-db-cnf
          configMap:
            name: {{ template "athenz-zms.mariadb.master.fullname" . }}
        {{- if .Values.mariadb.replication.enabled }}
        - name: slave-db-cnf
          configMap:
            name: {{ template "athenz-zms.mariadb.slave.fullname" . }}
        {{- end }}
        - name: script
          configMap:
            name: {{ template "athenz-zms.fullname" . }}-script
        - name: config
          configMap:
            name: {{ template "athenz-zms.fullname" . }}-config
        - name: zms-key
          secret:
            secretName: {{ template "athenz-zms.secretName" . }}
            items:
              - key: private.pem
                path: private.pem
                mode: 400
        - name: tls
          secret:
            secretName: {{ template "athenz-zms.tls.secretName" . }}
        - name: tls-ca
          secret:
            secretName: {{ template "athenz-zms.tls.ca.secretName" . }}
        - name: tls-stores
          emptyDir: {}
        - name: log
          emptyDir: {}
