{{- if (not .Values.existingTlsSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zms.tls.secretName" . }}
  labels:
    app: "{{ template "athenz-zms.name" . }}"
    chart: "{{ template "athenz-zms.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/secrets/tls/zms_cert.pem" | b64enc | nindent 4 }}
  tls.key: {{ .Files.Get "files/secrets/tls/zms_key.pem" | b64enc | nindent 4 }}
---
{{- end -}}
{{- if (not .Values.existingTlsCaSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zms.tls.ca.secretName" . }}
  labels:
    app: "{{ template "athenz-zms.name" . }}"
    chart: "{{ template "athenz-zms.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data: {{ (.Files.Glob "files/secrets/tls/CAs/*.pem").AsSecrets | nindent 2 }}
{{- end -}}
