{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zms.secretName" . }}
  labels:
    app: "{{ template "athenz-zms.name" . }}"
    chart: "{{ template "athenz-zms.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  private.pem: {{ .Files.Get "files/secrets/athenz/private.pem" | b64enc | nindent 4 }}
  {{- if not (empty .Values.athenz.password.keystore) -}}
  keystore: {{ .Values.athenz.password.keystore | b64enc | quote }}
  {{ else }}
  keystore: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end -}}
  {{- if not (empty .Values.athenz.password.truststore) -}}
  truststore: {{ .Values.athenz.password.truststore | b64enc | quote }}
  {{ else }}
  truststore: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end -}}
{{- end -}}
