apiVersion: v1
kind: Service
metadata:
  name: {{ template "athenz-zms.fullname" . }}
  labels:
    app: "{{ template "athenz-zms.name" . }}"
    chart: "{{ template "athenz-zms.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.service.annotations }}
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ClusterIP" }}
  {{- if .Values.service.clusterIp }}
  clusterIP: {{ .Values.service.clusterIp }}
  {{- end }}
  {{- end }}
  ports:
  - protocol: TCP
    name: zms
    port: {{ .Values.service.port }}
    targetPort: zms
{{- if eq .Values.service.type "NodePort" }}
{{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
{{- end }}
  selector:
    app: "{{ template "athenz-zms.name" . }}"
    release: "{{ .Release.Name }}"
